### PR TITLE
Add web app for Badge generator

### LINKED ISSUE #8: Create a React App to generate Peerlist README badges
The idea is to create a web app similar to [Badges Generator](https://badgesgenerator.com/) or [Shields.io](https://shields.io/) to generate Peerlist README badges. 

### Contributing guide

Please branch off from `feature/web-app` and raise a PR to `feature/web-app`. Currently, this branch contains a client directory that contains a basic React boilerplate which can be developed further as a React app to generate Peerlist badges dynamically. 

### API documentation

[Refer here](https://github.com/vinitshahdeo/peerlist-readme-badge#handshake-how-to-use) 🔗 

```markdown
![Peerlist](https://peerlist-readme-badge.herokuapp.com/api/vinitshahdeo)
```

Peerlist

> In case, you have other frameworks in mind, please check out a branch feature/web-app-<your framework> from `develop` and create your app within the client directory.

### PR DESCRIPTION
**Pull request by Manthan-Kuber**
closes #8

### CODE REVIEW

**Review by vinitshahdeo — APPROVED** [review]

**Comment by vinitshahdeo** [comment]
Great job @Manthan-Kuber 🥳 

Thanks for the PR.

**Comment by Manthan-Kuber** [comment]
> Great job @Manthan-Kuber 🥳
> 
> Thanks for the PR.

Thank you 😄. Can you please look into this ?

Screenshot_2022-10-02-14-10-30-12_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by vinitshahdeo** [comment]
@Manthan-Kuber Could you please check now?

**Comment by Manthan-Kuber** [comment]
@vinitshahdeo Nope still the same.
Screenshot_2022-10-04-17-09-33-36_40deb401b9ffe8e1df2f1cc5ba480b12
This is what's written here

**Comment by Manthan-Kuber** [comment]
@vinitshahdeo Donee. I got the mail.Thanks! Had fun contributing ! Also thanks for connecting with me on LinkedIn 😄

**Comment by vinitshahdeo** [comment]
Thanks for the contribution 🥳

**Pull request merged**
