### PR TITLE
Feat: option to attach peerlist profile link

### PR DESCRIPTION
**Pull request by ramdhanihendrie**
This PR is for issue #16

### CODE REVIEW

**Comment by vinitshahdeo** [comment]
Tracking the above issue here: #18

**Comment by vinitshahdeo** [comment]
@ramdhanihendrie Yes - tracking the issue separately #18. This is out of the scope of this PR. Great job 👏

**Review by vinitshahdeo — APPROVED** [review]

**Comment by ramdhanihendrie** [comment]
Would you like to add a `hacktoberfest-accepted` label to this PR? Thanks

**Comment by vinitshahdeo** [comment]
Sure - @ramdhanihendrie added the label. Please check if you could open some beginner-friendly issues for this project. I just want to open some first-timers issues so that beginners can kickstart their open-source journey.

**Pull request merged**
